class: SimpleJsonPrompter
prompt: gen_json_paper.txt
output_key: summary
generator_type: openai
generator_model_name: gpt-4o
generator_extra_gen_params: "{'response_format': {'type': 'json_object'}}"
