class: SimpleJsonPrompter
prompt: gen_json_paper.txt
output_key: summary
generator_type: gemini
generator_model_name: gemini-2.0-flash
generator_extra_gen_params: "{'config': {'response_mime_type': 'application/json',}}"
