class: SimpleJsonPrompter
prompt: rag_json.txt
output_key: summary
generator_type: openai
generator_model_name: gpt-4o
generator_extra_gen_params: "{'response_format': {'type': 'json_object'}}"
no_issue_keyword: "No issue"
