method: cumulative
class: SimpleJsonPrompter
error_classification_prompt: "prompt_report_cumulative_choosetype.txt"
error_classification_output_key: "answer"
error_name_prefix: "type_"
error_name_key: "error_name"
error_description_key: "error_description"
error_type_generation_prompt: "prompt_report_cumulative_newtype.txt"
error_type_generation_output_key: "answer"
error_type_regeneration_prompt: "prompt_report_cumulative_regenerate_type_names.txt"
error_type_regeneration_output_key: "answer"
generator_type: "gemini"
generator_model_name: "gemini-2.0-flash"
generator_extra_gen_params: "{'config': {'response_mime_type': 'application/json',}}"
regenerate_cluster_names: True
